CREATE TABLE "web-dev_file_upload" (
	"id" serial PRIMARY KEY NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"file_size" bigint NOT NULL,
	"mime_type" varchar(128) NOT NULL,
	"file_data" text NOT NULL,
	"uploaded_by" varchar(256) NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "web-dev_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "web-dev_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "file_name_idx" ON "web-dev_file_upload" USING btree ("file_name");--> statement-breakpoint
CREATE INDEX "uploaded_by_idx" ON "web-dev_file_upload" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX "status_idx" ON "web-dev_file_upload" USING btree ("status");--> statement-breakpoint
CREATE INDEX "name_idx" ON "web-dev_post" USING btree ("name");